parameters:
  rootpath: '/blog/'

stages:
- stage:
  displayName: 'Generate blog contents by Hexo'
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        cd $(Build.Repository.LocalPath)
        sed -i -e "s|root: .*|root: ${{ parameters.rootpath }}|g" _config.yml
        echo "================================"
        echo " Content of updated _config.yml"
        echo "================================"
        cat _config.yml
      displayName: 'Update _config.yml'

    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'
    
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: '$(Build.Repository.LocalPath)'
      displayName: 'Install Npm'

    - script: |
        sudo npm install -g hexo
      displayName: 'Install hexo'

    - script: |
        hexo generate
      displayName: 'Generate blog by hexo'
    
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'public'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/blog.zip'
        replaceExistingArchive: true
      
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'
